"""Pytest Configuration and Automatic Test Data Sanitizer.

Ensures that no test artifacts (dummy tasks, test transactions, fake peer debts,
or dummy memories) persist in the database after any test suite execution.
"""

from __future__ import annotations

import logging
import pytest

logger = logging.getLogger("vesper.tests.conftest")


def _wipe_test_residue() -> None:
    """Removes all test-generated records across Supabase tables."""
    try:
        from backend.data.client import get_supabase_client
        sb = get_supabase_client()
    except Exception as e:
        logger.debug(f"[conftest] Skipping DB cleanup; Supabase not configured: {e}")
        return

    try:
        # 1. Clean up test tasks
        sb.table("tasks").delete().ilike("title", "%Test%").execute()
        sb.table("tasks").delete().eq("metadata->>tag", "TEST").execute()

        # 2. Clean up test transactions
        sb.table("transactions").delete().ilike("description", "%pytest%").execute()
        sb.table("transactions").delete().ilike("description", "%test%").execute()
        sb.table("transactions").delete().eq("category", "Test Category").execute()

        # 3. Clean up test debts
        sb.table("debts").delete().ilike("person", "Partner %").execute()

        # 4. Clean up test recurring rules
        sb.table("recurring_transactions").delete().ilike("name", "%Pytest%").execute()

        # 5. Clean up test shodh memories
        sb.table("shodh_memories").delete().ilike("statement", "%ambient jazz at midnight%").execute()
        sb.table("shodh_memories").delete().ilike("statement", "%pytest%").execute()
    except Exception as e:
        logger.debug(f"[conftest] Note: DB cleanup encountered non-fatal error: {e}")


@pytest.fixture(scope="session", autouse=True)
def wipe_test_data_session():
    """Autouse fixture running at both the start and end of every test session."""
    # Pre-test cleanup: ensure a clean slate
    _wipe_test_residue()
    yield
    # Post-test cleanup: wipe any records generated by tests
    _wipe_test_residue()
