"""VESPER 2-Stage Plan-and-Execute Engine.

Stage 1: Uses fast LPU model (Groq compound-mini) to decompose the query into:
  - 'direct': Pure conversational / general reasoning without tools.
  - 'parallel': Independent tasks dispatched concurrently via `asyncio.gather()`.
  - 'sequential': Dependent chained tasks (e.g., Search -> Play on Spotify).
Stage 2: Dispatches tasks to registered specialists in the swarm.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
import time
from typing import Any, Dict, List, Optional, Tuple
from pydantic import BaseModel, Field

from backend.agent.llm import LLMClient
from backend.agent.registry import SpecialistRegistry
from backend.agent.specialists.base import SpecialistResult

logger = logging.getLogger("vesper.agent.planner")


class SwarmPlan(BaseModel):
    """Execution plan generated by the Stage 1 Planner."""

    plan_type: str = "direct"  # "direct", "parallel", "sequential"
    direct_response: Optional[str] = None
    steps: List[Dict[str, Any]] = Field(default_factory=list)


class ExecutionResult(BaseModel):
    """Aggregate result from plan execution."""

    plan_type: str = "direct"
    direct_response: Optional[str] = None
    specialist_results: List[SpecialistResult] = Field(default_factory=list)
    planning_latency_ms: float = 0.0
    execution_latency_ms: float = 0.0


PLANNER_SYSTEM_PROMPT = """You are the Stage 1 Execution Planner for VESPER (supervised by Alfred).
Analyze the user's intent and produce an optimal execution plan.

{capabilities}

Routing Rules:
1. Tool Invocation Priority:
   - Optical Perception & Webcam OCR (Primary): When user asks what they are holding, showing, wearing, or asks to inspect, read, transcribe, or perform OCR on a physical item/book/paper/document in front of them (e.g. "what am I holding", "inspect this", "look at my webcam", "read what's on this paper", "OCR this book", "what does this document say"), ALWAYS call 'vision' with 'inspect_webcam' or 'ocr_webcam'.
   - Screen & Monitor Perception: When the user specifically asks about what is displayed on their computer screen, monitor, terminal, or window (e.g. "what error is on my screen", "inspect my desktop", "OCR my terminal screen"), ALWAYS call 'vision' with 'inspect_screen' or 'ocr_screen'.
   - Long-Term Personal Memory & Profile: When the user asks to remember personal facts/habits/preferences, recalls personal knowledge, asks what you know about them, or asks to forget a fact (e.g. "remember that I prefer dark roast coffee", "what coffee do I like", "what do you know about me", "forget my old gym routine"), ALWAYS call 'memory' with 'store_memory', 'recall_memory', 'get_user_profile', or 'forget_memory'.
   - Personal Finance & Debts: When the user asks about money, balances, expenses, income, spending, splitting bills, lending, borrowing, who owes whom, or financial goals (e.g. "log ₹450 on food", "what's my balance", "split ₹1800 with Rohit", "who owes me money", "set a savings goal"), ALWAYS call 'finance' with 'get_balance', 'log_transaction', 'split_expense', 'manage_debt', or 'manage_financial_goal'.
   - System Vitals & Hardware: When the user asks about PC hardware, CPU, RAM, disk, thermals, heavy processes, or audio control (e.g. "system vitals", "how much RAM is used", "what is using the most CPU", "is docker running", "set volume to 70%"), ALWAYS call 'system' with 'get_system_vitals', 'get_top_processes', 'query_process', 'set_volume', 'set_mute', or 'list_audio_sinks'.
   - Web Search & Research: When the user asks about current events, news, live facts, technical documentation, or quick lookups (e.g. "search for the latest SpaceX launch", "who won the game", "look up quantum computing"), ALWAYS call 'research' with action 'web_search' or 'quick_lookup'.
   - Web Page Crawling & Scraping: When the user provides a URL or asks to scrape, read, or summarize a specific webpage (e.g. "read https://...", "summarize this page", "scrape the documentation at ..."), ALWAYS call 'crawl' with action 'scrape_and_summarize' or 'crawl_url'.
   - Video / Content Search: When the user asks for videos, YouTube clips, channel uploads, or creators (e.g. "search for the latest video by mr whos the boss", "watch video"), ALWAYS call 'media' with action 'search_youtube_video'.
   - Music & Audio: When the user asks to play a song, artist, album, or playlist, call 'media' with 'play_track' or 'play_playlist'. For player control (pause, resume, skip), call 'media' with 'control_playback'.
   - Tasks & Schedules: When the user asks to add, list, complete tasks, or check today's agenda/calendar, ALWAYS call 'tasks' with 'add_task', 'list_tasks', 'complete_task', or 'get_daily_agenda'.
   - Tolerate informal language, phonetic spelling, and typos (e.g. "seach" -> search, "whos the boss" -> mrwhosetheboss, "calender" -> calendar).

2. Plan Types:
   - "parallel": Use for one or more independent actions (e.g. searching the web, checking finances, checking CPU, adding a task, or doing both simultaneously).
   - "sequential": Use when one step depends on the output of a prior step.
     Example: If user asks "Search for the latest Next.js 16 update and summarize the article":
     Step 1: {{"agent": "research", "action": "web_search", "params": {{"query": "latest Next.js 16 update"}}}}
     Step 2: {{"agent": "crawl", "action": "scrape_and_summarize", "params": {{"url": "$step_1.result.top_url"}}}}
   - "direct": Use ONLY for simple greetings ("hello", "good morning"), casual banter, or pure philosophical queries that do not involve tasks, schedules, finances, hardware, videos, research, or music.

You MUST return strictly valid JSON matching this schema:
{{
  "plan_type": "parallel" | "sequential" | "direct",
  "direct_response": null | "string",
  "steps": [
    {{
      "agent": "specialist_name",
      "action": "action_name",
      "params": {{}}
    }}
  ]
}}
"""


class SwarmPlanner:
    """Orchestrates 2-stage planning and dynamic specialist execution."""

    def __init__(self, llm_client: Optional[LLMClient] = None) -> None:
        self.llm = llm_client or LLMClient()

    async def create_plan(self, query: str, registry: SpecialistRegistry) -> Tuple[SwarmPlan, float]:
        """Stage 1: Generates an execution plan from the user query."""
        capabilities_text = registry.get_capabilities_prompt()
        prompt = PLANNER_SYSTEM_PROMPT.format(capabilities=capabilities_text)

        messages = [
            {"role": "system", "content": prompt},
            {"role": "user", "content": query},
        ]

        plan_data, elapsed_ms = await self.llm.generate_json(messages, temperature=0.1)

        try:
            plan = SwarmPlan(**plan_data)
            if plan.steps and plan.plan_type == "direct":
                plan.plan_type = "parallel"
        except Exception as e:
            logger.warning(f"[Planner] Plan parsing fallback: {e}. Defaulting to direct.")
            plan = SwarmPlan(plan_type="direct", direct_response="How may I be of service, sir?")

        return plan, elapsed_ms

    async def execute_plan(
        self,
        plan: SwarmPlan,
        registry: SpecialistRegistry,
        context: Optional[Dict[str, Any]] = None,
    ) -> ExecutionResult:
        """Stage 2: Executes the plan across the registered specialist swarm."""
        t0 = time.perf_counter()

        if plan.plan_type == "direct" or not plan.steps:
            return ExecutionResult(
                plan_type="direct",
                direct_response=plan.direct_response,
                specialist_results=[],
                execution_latency_ms=(time.perf_counter() - t0) * 1000,
            )

        # ── Parallel Execution (Independent Steps) ───────────────────────────
        if plan.plan_type == "parallel":
            tasks = [
                registry.execute_action(
                    agent_name=step.get("agent", ""),
                    action=step.get("action", ""),
                    params=step.get("params", {}),
                    context=context,
                )
                for step in plan.steps
            ]
            results = await asyncio.gather(*tasks, return_exceptions=False)
            exec_ms = (time.perf_counter() - t0) * 1000
            return ExecutionResult(
                plan_type="parallel",
                specialist_results=list(results),
                execution_latency_ms=exec_ms,
            )

        # ── Sequential Execution (Chained Steps) ─────────────────────────────
        results: List[SpecialistResult] = []
        step_outputs: Dict[str, Any] = {}

        for idx, step in enumerate(plan.steps, start=1):
            agent_name = step.get("agent", "")
            action = step.get("action", "")
            params = step.get("params", {}).copy()

            # Dynamic variable interpolation (e.g., "$step_1.result.top_result" or "$step_1.top_result")
            for k, v in params.items():
                if isinstance(v, str) and v.startswith("$step_"):
                    match = re.match(r"\$step_(\d+)(?:\.(.+))?", v)
                    if match:
                        ref_step = f"step_{match.group(1)}"
                        ref_prop = match.group(2)
                        ref_data = step_outputs.get(ref_step, {})

                        if ref_prop:
                            parts = [p for p in ref_prop.split(".") if p not in ("result", "data")]
                            curr = ref_data
                            for p in parts:
                                if isinstance(curr, dict) and p in curr:
                                    curr = curr[p]
                                else:
                                    break
                            params[k] = curr
                        else:
                            params[k] = ref_data

            res = await registry.execute_action(agent_name, action, params, context)
            results.append(res)
            step_outputs[f"step_{idx}"] = res.data or res.speech_summary

        exec_ms = (time.perf_counter() - t0) * 1000
        return ExecutionResult(
            plan_type="sequential",
            specialist_results=results,
            execution_latency_ms=exec_ms,
        )
