"""VESPER 2-Stage Plan-and-Execute Engine.

Stage 1: Uses fast LPU model (Groq compound-mini) to decompose the query into:
  - 'direct': Pure conversational / general reasoning without tools.
  - 'parallel': Independent tasks dispatched concurrently via `asyncio.gather()`.
  - 'sequential': Dependent chained tasks (e.g., Search -> Play on Spotify).
Stage 2: Dispatches tasks to registered specialists in the swarm.
"""

from __future__ import annotations

import asyncio
import datetime
import json
import logging
import re
import time
from typing import Any, Dict, List, Optional, Tuple
from pydantic import BaseModel, Field

from backend.agent.llm import LLMClient
from backend.agent.proactive.action_queue import action_queue
from backend.agent.proactive.audit_logger import audit_logger
from backend.agent.registry import SpecialistRegistry
from backend.agent.semantic_router import SemanticIntent, SemanticIntentRouter
from backend.agent.specialists.base import SpecialistResult
from backend.agent.title_normalizer import build_action, classify_action_type, extract_time_phrase, normalize_title

logger = logging.getLogger("vesper.agent.planner")


class SwarmPlan(BaseModel):
    """Execution plan generated by the Stage 1 Planner."""

    plan_type: str = "direct"  # "direct", "parallel", "sequential"
    direct_response: Optional[str] = None
    steps: List[Dict[str, Any]] = Field(default_factory=list)
    provider_used: Optional[str] = "unknown"


class ExecutionResult(BaseModel):
    """Aggregate result from plan execution."""

    plan_type: str = "direct"
    direct_response: Optional[str] = None
    specialist_results: List[SpecialistResult] = Field(default_factory=list)
    planning_latency_ms: float = 0.0
    execution_latency_ms: float = 0.0
    provider_used: Optional[str] = None


PLANNER_SYSTEM_PROMPT = """You are the Stage 1 Execution Planner for VESPER (supervised by Alfred).
Analyze the user's intent and produce an optimal execution plan matching the schema.

CURRENT TEMPORAL CONTEXT:
- System Date & Time: {current_datetime}
- Day of Week: {current_day}

{capabilities}

PLANNING RULES:
1. Plan Types:
   - "parallel": DEFAULT for all single or multi-intent tasks fetching real-world data independently (e.g. weather + music, task + calendar, email search + news).
   - "sequential": ONLY when step N+1 needs data produced by step N via '$step_<idx>.<property>'.
     Examples:
     * Search email then read thread: step 2 params: {{"thread_id": "$step_1.thread_id", "email_id": "$step_1.id"}}
     * Media status then origin research: step 2 params: {{"query": "$step_1.track movie"}}
     * Webcam/Screen OCR then web search: step 2 params: {{"query": "$step_1.extracted_text"}}
   - "direct": ONLY for conversational greetings ("hello") or when answer is resolved completely from ACTIVE SESSION CONTEXT.

2. Perception vs Mobile Notifications:
   - Screen/Display: Use 'vision:inspect_screen' or 'vision:ocr_screen' ONLY for computer monitor, IDE, windows, or desktop errors.
   - Physical/Camera: Use 'vision:inspect_webcam' or 'vision:ocr_webcam' for handheld objects, documents, or physical surroundings.
   - Mobile Notifications & Chat Messages: ALWAYS use 'tasks:search_mobile_notifications' or 'tasks:list_mobile_notifications' for WhatsApp, Slack, Telegram, SMS, or phone alerts. NEVER use 'vision:ocr_screen' or 'vision:inspect_screen' for mobile notifications or chat messages unless the user explicitly refers to their computer monitor or screen!

3. Tasks vs Reminders vs Events:
   - General todo without alarm: 'tasks:add_task' or 'tasks:list_tasks'.
   - Time-anchored alarm clock: 'tasks:set_reminder' or 'tasks:list_reminders'.
   - Calendar meeting/agenda: 'tasks:schedule_event', 'tasks:list_calendar_events', 'tasks:get_daily_agenda'.
   - Renaming / Updating / Rescheduling: 'tasks:update_task' with params: {{"query": "<existing title or time>", "new_title": "<new title>", "new_time": "<optional new time>"}}.
   - Deleting / Removing: 'tasks:delete_task' with params: {{"title": "<title or time to remove>"}}.

4. Web Search:
   - Plan 'research:web_search' for real-world facts, trivia, movie origins, directors, weather, or explicit search queries.

5. Critical Conversation Scope & Anti-Duplication:
   - Plan steps STRICTLY and EXCLUSIVELY for the CURRENT USER QUERY.
   - Any provided conversation history is SOLELY for resolving pronouns or references (e.g., 'it', 'him', 'that email').
   - NEVER re-execute, repeat, or append tasks from earlier conversation turns or completed past queries.

6. Email Dispatch & Drafts:
   - When the user asks to "send [report/notes/summary/email] to [person/email]" or "write/draft an email to [person/email]":
     * ALWAYS route to 'email:draft_email' with params: {{"to": "<email_or_recipient>", "subject": "<subject>", "body": "<body>"}}.
     * NEVER route sending an email, notes, or research report as 'tasks:add_task'!
     * If the user refers to recent research (e.g. "that report"), populate body with the research content.

7. Temporal Grounding & Relative Dates:
   - Base reference date and time is {current_datetime} ({current_day}).
   - Relative terms ('today', 'yesterday', 'tomorrow', 'tonight', 'next week', 'this morning') must be resolved relative to this reference point.
   - For daily agenda or today's tasks ('what are my tasks today', 'today's agenda', 'what do I have scheduled today'): route to 'tasks:get_daily_agenda' with params: {{"date": "today", "query": "<user query>"}}.

8. Personal Finances & Accounts:
   - When the user asks about financial standing ("how am I doing financially", "how are my finances"), net worth, multi-account holdings (Union Bank, SBI, Saraswat, Cash), or debts: ALWAYS route to 'finance:get_financial_summary' or 'finance:get_balance'.
   - When the user asks to view recent transactions, expenses, or spends: route to 'finance:list_transactions'.
   - When the user asks to check bank emails or transaction alerts in their mailbox: route to 'email:search_emails' with the bank or transaction query.
   - NEVER route general financial inquiries to mobile SMS notifications! Mobile notifications ('tasks:search_mobile_notifications') are strictly for phone alerts (WhatsApp, Slack, Telegram, SMS) when explicitly mentioned by the user.

FEW-SHOT EXAMPLES:
- Financial standing: {{"plan_type": "parallel", "steps": [{{"agent": "finance", "action": "get_financial_summary", "params": {{}}}}]}}
- Bank balance: {{"plan_type": "parallel", "steps": [{{"agent": "finance", "action": "get_balance", "params": {{"account_name": "Saraswat"}}}}]}}
- Bank email transaction: {{"plan_type": "parallel", "steps": [{{"agent": "email", "action": "search_emails", "params": {{"query": "Saraswat Bank transaction"}}}}]}}
- Reminder: {{"plan_type": "parallel", "steps": [{{"agent": "tasks", "action": "set_reminder", "params": {{"reminder": "Pick up my mom", "time": "5:45 PM today"}}}}]}}
- Task: {{"plan_type": "parallel", "steps": [{{"agent": "tasks", "action": "add_task", "params": {{"title": "Deploy backend"}}}}]}}
- Event: {{"plan_type": "parallel", "steps": [{{"agent": "tasks", "action": "schedule_event", "params": {{"summary": "Meeting with Rohit", "start_time": "tomorrow at 3pm"}}}}]}}
- Rename event: {{"plan_type": "parallel", "steps": [{{"agent": "tasks", "action": "update_task", "params": {{"query": "9 o'clock event", "new_title": "AWS Workshop"}}}}]}}
- Remove event: {{"plan_type": "parallel", "steps": [{{"agent": "tasks", "action": "delete_task", "params": {{"title": "8 o'clock event"}}}}]}}
- Handheld: {{"plan_type": "sequential", "steps": [{{"agent": "vision", "action": "ocr_webcam", "params": {{"focus_hint": "title/label"}}}}, {{"agent": "research", "action": "web_search", "params": {{"query": "$step_1.extracted_text"}}}}]}}
- Multi-intent: {{"plan_type": "parallel", "steps": [{{"agent": "media", "action": "play_music", "params": {{"query": "lofi"}}}}, {{"agent": "tasks", "action": "add_task", "params": {{"title": "Review PR"}}}}]}}
- Screen error: {{"plan_type": "parallel", "steps": [{{"agent": "vision", "action": "inspect_screen", "params": {{"query": "error"}}}}]}}
- Read thread: {{"plan_type": "parallel", "steps": [{{"agent": "email", "action": "read_thread", "params": {{}}}}]}}
- Current weather: {{"plan_type": "parallel", "steps": [{{"agent": "weather", "action": "get_current_weather", "params": {{"location": "Mumbai"}}}}]}}
- Weather forecast: {{"plan_type": "parallel", "steps": [{{"agent": "weather", "action": "get_weather_forecast", "params": {{"location": "Palghar", "days": 3}}}}]}}
- Will it rain: {{"plan_type": "parallel", "steps": [{{"agent": "weather", "action": "check_rain", "params": {{"hours_ahead": 6}}}}]}}
- Greet/chit-chat: {{"plan_type": "parallel", "steps": [{{"agent": "conversation", "action": "chit_chat", "params": {{"query": "how are you doing"}}}}]}}
- Recall conversations: {{"plan_type": "parallel", "steps": [{{"agent": "conversation", "action": "recall_conversations", "params": {{"query": "vesper project", "time_range": "week"}}}}]}}

Return strictly JSON:
{{
  "plan_type": "parallel" | "sequential" | "direct",
  "direct_response": null | "string",
  "steps": [{{"agent": "specialist_name", "action": "action_name", "params": {{}}}}]
}}"""


class SwarmPlanner:
    """Orchestrates 2-stage planning and dynamic specialist execution."""

    def __init__(
        self,
        llm_client: Optional[LLMClient] = None,
        semantic_router: Optional[SemanticIntentRouter] = None,
    ) -> None:
        self.llm = llm_client or LLMClient()
        self.semantic_router = semantic_router or SemanticIntentRouter.get_instance()

    def _match_staged_action_by_phrase(self, query: str) -> Tuple[List[Any], List[Any]]:
        """Matches active staged actions against entity or domain keywords in query.

        Returns (positive_matches, negative_matches).
        """
        q_lower = query.lower()
        active = action_queue.get_active_actions()
        if not active:
            return [], []

        pos_candidates = []
        neg_candidates = []

        is_neg = bool(re.search(r"\b(no|don't|dont|cancel|reject|never mind|nevermind|forget it|stop|discard)\b", q_lower))
        is_affirmative = bool(re.search(r"\b(yes|yeah|sure|confirm|proceed|go ahead|do it|add|create|log|record|that)\b", q_lower))

        for item in active:
            matched = False
            domain_lower = item.domain.lower()
            # Check domain and common synonyms
            if (
                domain_lower in q_lower
                or (domain_lower == "tasks" and any(k in q_lower for k in ("task", "todo", "reminder", "item", "form", "job", "internship")))
                or (domain_lower == "finance" and any(k in q_lower for k in ("transaction", "expense", "payment", "money", "debt", "budget", "rupees", "inr")))
                or (domain_lower == "system" and any(k in q_lower for k in ("process", "kill", "cpu", "load", "task", "pid")))
            ):
                matched = True

            # Check merchant or key tokens from verbatim text or params
            v_lower = item.verbatim_text.lower()
            tokens = [t.strip(",.:'\"") for t in v_lower.split() if len(t) > 3 and t not in ("under", "with", "from", "that", "this", "your")]
            for tok in tokens:
                if tok in q_lower:
                    matched = True
                    break

            # Check specific params (e.g. description or title)
            desc = str(item.params.get("description") or item.params.get("title") or "").lower()
            if desc and any(w in q_lower for w in desc.split() if len(w) > 3 and w not in ("under", "with", "from", "that", "this")):
                matched = True

            if matched:
                if is_neg:
                    neg_candidates.append(item)
                else:
                    pos_candidates.append(item)

        # If only 1 action is active across the cluster and user provides a targeted confirmation like
        # "yeah create that task", "create that", "cancel that", "do it", automatically match it!
        is_targeted = bool(re.search(r"\b(task|todo|transaction|expense|payment|item|form|job|it|that|this|matter)\b", q_lower))
        if len(active) == 1 and not pos_candidates and not neg_candidates and is_targeted and (is_affirmative or is_neg):
            if is_neg:
                neg_candidates.append(active[0])
            else:
                pos_candidates.append(active[0])

        return pos_candidates, neg_candidates

    def _check_deterministic_prefilter(
        self,
        query: str,
        session_context: Optional[Dict[str, Any]] = None,
        registry: Optional[SpecialistRegistry] = None,
    ) -> Optional[SwarmPlan]:
        """Pre-filters high-stakes unambiguous queries deterministically before LLM invocation.

        Tier 1: 0ms exact cache lookups and explicit hardware commands.
        Tier 2: ~10ms local semantic similarity router using all-MiniLM-L6-v2 (0 Groq tokens).
        """
        q_lower = query.lower()

        # ── TIER 1: DETERMINISTIC EXACT CACHE & HARDWARE RETRIEVAL (<1ms, 0 tokens) ──

        # 0a. Proactive Undo / Rollback Handler:
        is_undo = bool(
            re.search(
                r"\b(undo|rollback|reverse|revert)\s*(the\s+|my\s+|that\s+)?(last\s+)?(transaction|expense|payment|action|change)?\b",
                q_lower,
            )
        )
        if is_undo:
            last_action = audit_logger.get_last_action()
            if last_action and last_action.get("domain") == "finance":
                target_txn = (last_action.get("rollback_data") or {}).get("transaction_id")
                audit_logger.record_undo(last_action.get("action_id", ""), success=True)
                logger.info(f"[Planner.PreFilter] Proactive undo triggered for finance action: {last_action.get('action_id')}")
                return SwarmPlan(
                    plan_type="parallel",
                    provider_used="prefilter",
                    steps=[{
                        "agent": "finance",
                        "action": "undo_transaction",
                        "params": {"transaction_id": target_txn} if target_txn else {},
                    }],
                )
            elif any(w in q_lower for w in ["transaction", "expense", "payment", "money", "rupees", "inr"]):
                logger.info("[Planner.PreFilter] Undo transaction requested -> finance:undo_transaction")
                return SwarmPlan(
                    plan_type="parallel",
                    provider_used="prefilter",
                    steps=[{"agent": "finance", "action": "undo_transaction", "params": {}}],
                )

        # 0b. Proactive Staged Action Review / Inquiry:
        if any(p in q_lower for p in ["pending actions", "staged actions", "review pending", "pending matters", "what's staged", "what is staged"]):
            active = action_queue.get_active_actions()
            if not active:
                return SwarmPlan(
                    plan_type="direct",
                    provider_used="prefilter",
                    direct_response="You have no pending matters staged for review, sir.",
                )
            lines = [f"{i+1}. {a.verbatim_text}" for i, a in enumerate(active)]
            return SwarmPlan(
                plan_type="direct",
                provider_used="prefilter",
                direct_response=f"You have {len(active)} matter(s) staged for review, sir: " + "; ".join(lines),
            )

        # 0c. Proactive Confirmation & Disambiguation (3-Tier):
        pos_matches, neg_matches = self._match_staged_action_by_phrase(query)
        if len(neg_matches) == 1:
            target = neg_matches[0]
            action_queue.resolve_action(target.id, "rejected", confirmed_by="voice_domain_anchored")
            logger.info(f"[Planner.PreFilter] Domain-anchored rejection of staged action: {target.id}")
            return SwarmPlan(
                plan_type="direct",
                provider_used="prefilter",
                direct_response=f"Very well, sir. I have dismissed and discarded the proposal: {target.verbatim_text}.",
            )
        elif len(neg_matches) > 1:
            return SwarmPlan(
                plan_type="direct",
                provider_used="prefilter",
                direct_response="Sir, you have multiple matching matters staged. Would you care to specify which one to cancel?",
            )

        if len(pos_matches) == 1:
            target = pos_matches[0]
            action_queue.resolve_action(target.id, "confirmed", confirmed_by="voice_domain_anchored")
            audit_logger.log_action(target, confirmed_by="voice_domain_anchored")
            logger.info(f"[Planner.PreFilter] Domain-anchored confirmation of staged action: {target.id}")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{
                    "agent": target.domain,
                    "action": target.action,
                    "params": target.params,
                }],
            )
        elif len(pos_matches) > 1:
            return SwarmPlan(
                plan_type="direct",
                provider_used="prefilter",
                direct_response="Sir, you have multiple pending matters staged. Would you care to specify which one you wish to confirm?",
            )

        # Fallback to strict 15s window for bare affirmative/negative without domain keyword
        recent_prompted = action_queue.get_recent_prompted_action(max_age_sec=15.0)
        if recent_prompted:
            is_affirmative = any(
                re.search(rf"\b{w}\b", q_lower)
                for w in ["yes", "yeah", "sure", "confirm", "proceed", "go ahead", "do it", "log it", "record it", "add it", "create it", "pause it", "play it", "resume it", "create that task", "add that task"]
            ) and not any(w in q_lower for w in ["don't", "dont", "no", "cancel", "stop", "nevermind", "forget"])

            is_negative = any(
                re.search(rf"\b{w}\b", q_lower)
                for w in ["no", "don't", "dont", "cancel", "reject", "never mind", "nevermind", "forget it", "stop", "discard"]
            )

            if is_affirmative:
                action_queue.resolve_action(recent_prompted.id, "confirmed", confirmed_by="voice_proactive_window")
                audit_logger.log_action(recent_prompted, confirmed_by="voice_proactive_window")
                logger.info(f"[Planner.PreFilter] Proactive window confirmation for staged action: {recent_prompted.id}")
                return SwarmPlan(
                    plan_type="parallel",
                    provider_used="prefilter",
                    steps=[{
                        "agent": recent_prompted.domain,
                        "action": recent_prompted.action,
                        "params": recent_prompted.params,
                    }],
                )
            elif is_negative:
                action_queue.resolve_action(recent_prompted.id, "rejected", confirmed_by="voice_15s_window")
                logger.info(f"[Planner.PreFilter] Strict 15s window rejection for staged action: {recent_prompted.id}")
                return SwarmPlan(
                    plan_type="direct",
                    provider_used="prefilter",
                    direct_response="Understood, sir. I have discarded that proposal.",
                )

        # 0d. Pending Email Draft Confirmation or Cancellation:
        pending_draft = None
        if session_context:
            pending_draft = session_context.get("pending_email_draft")
            entities = session_context.get("entities")
            if not pending_draft and isinstance(entities, dict):
                pending_draft = entities.get("email_draft")

        if pending_draft:
            cur_to = str(pending_draft.get("to", "")).strip()

            # 0a. Check if user provides a full email address to complete or replace recipient
            email_match = re.search(r"([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)", query)
            if email_match:
                new_email = email_match.group(1).strip()
                pending_draft["to"] = new_email
                logger.info(f"[Planner.PreFilter] Updated pending draft recipient to full email: {new_email}")
                return SwarmPlan(
                    plan_type="direct",
                    provider_used="prefilter",
                    direct_response=f"I have set the recipient address to {new_email}, sir. Would you like me to send the email now?",
                )

            # 0b. Check if user provides a domain completion (e.g. "@gmail.com" or "gmail.com")
            # to complete an existing handle that lacks a domain
            domain_match = re.search(r"@([a-zA-Z0-9-]+\.[a-zA-Z]{2,})", query) or re.search(
                r"^\s*(?:it is\s+)?([a-zA-Z0-9-]+\.(?:com|net|org|io|ai|in|edu|gov|co|app|tech))\s*$",
                query,
                re.IGNORECASE,
            )
            if domain_match:
                domain = domain_match.group(1).strip()
                handle = cur_to.split("@")[0].strip() if cur_to else "user"
                merged_email = f"{handle}@{domain}"
                pending_draft["to"] = merged_email
                logger.info(f"[Planner.PreFilter] Merged pending draft recipient domain: {merged_email}")
                return SwarmPlan(
                    plan_type="direct",
                    provider_used="prefilter",
                    direct_response=f"I have set the recipient address to {merged_email}, sir. Would you like me to dispatch the email now?",
                )

            # 0c. Check if user modifies subject: e.g. "change subject to Meeting Tomorrow [and send it]"
            subject_match = re.search(
                r"(?:change|set|update)\s+(?:the\s+)?subject\s+(?:to|as)\s+[\"']?(.*?)[\"']?$",
                query,
                re.IGNORECASE,
            )
            if subject_match:
                raw_subj = subject_match.group(1).strip()
                dispatch_now = False
                send_in_subj = re.search(r"(?:,\s*|\s+)(?:and\s+|then\s+|now\s+)?(?:send\s+it|send|dispatch)\s*[.!]?$", raw_subj, re.IGNORECASE)
                if send_in_subj:
                    new_subject = raw_subj[:send_in_subj.start()].strip()
                    dispatch_now = True
                else:
                    new_subject = raw_subj.rstrip(".! ")
                pending_draft["subject"] = new_subject
                if session_context:
                    ctx_entities = session_context.get("entities")
                    if isinstance(ctx_entities, dict) and isinstance(ctx_entities.get("email_draft"), dict):
                        ctx_entities["email_draft"]["subject"] = new_subject
                if dispatch_now:
                    from backend.agent.specialists.email_specialist import is_valid_email
                    if not is_valid_email(cur_to):
                        return SwarmPlan(
                            plan_type="direct",
                            provider_used="prefilter",
                            direct_response=f"I have updated the subject to '{new_subject}', sir. However, '{cur_to}' is not a complete email address with a domain. What is the recipient's full email address?",
                        )
                    return SwarmPlan(
                        plan_type="parallel",
                        provider_used="prefilter",
                        steps=[{
                            "agent": "email",
                            "action": "send_email",
                            "params": {
                                "to": cur_to,
                                "subject": new_subject,
                                "body": pending_draft.get("body", ""),
                            }
                        }],
                    )
                else:
                    return SwarmPlan(
                        plan_type="direct",
                        provider_used="prefilter",
                        direct_response=f"I have updated the subject to '{new_subject}', sir. Would you like me to dispatch the email now?",
                    )

            # 0d. Check if user adds or updates message content/body (with optional immediate send)
            send_suffix = re.search(
                r"(?:,\s*|\s+)(?:and\s+|then\s+|now\s+)?(?:send\s+it|send\s+that(?:\s+email)?|send|dispatch(?:\s+it)?|shoot(?:\s+it)?|fire\s+it)\s*[.!]?$",
                query,
                re.IGNORECASE,
            )
            has_send_suffix = bool(send_suffix)
            query_without_send = query[:send_suffix.start()].strip() if send_suffix else query.strip()

            body_match = re.search(
                r"^\s*(?:please\s+)?(?:add\s+that\s+saying|add\s+saying|add\s+that|saying|write\s+that|write|tell\s+(?:him|her|them)\s+that|tell\s+(?:him|her|them)|the\s+body\s+(?:is|should\s+be)|the\s+message\s+(?:is|should\s+be)|the\s+content\s+(?:is|should\s+be)|put\s+(?:in\s+the\s+body|as\s+body)|say|add|include\s+that|include)\s*[:,\-]?\s*[\"']?(.*?)[\"']?\s*$",
                query_without_send,
                re.IGNORECASE,
            )
            if body_match and body_match.group(1).strip():
                new_text = body_match.group(1).strip()
                cur_body = pending_draft.get("body", "").strip()
                if cur_body and re.search(r"^\s*add", query, re.IGNORECASE):
                    merged_body = f"{cur_body}\n{new_text}"
                else:
                    merged_body = new_text

                pending_draft["body"] = merged_body
                if session_context:
                    ctx_entities = session_context.get("entities")
                    if isinstance(ctx_entities, dict) and isinstance(ctx_entities.get("email_draft"), dict):
                        ctx_entities["email_draft"]["body"] = merged_body

                logger.info(f"[Planner.PreFilter] Updated pending email draft body: '{merged_body[:60]}' (send_now={has_send_suffix})")

                if has_send_suffix:
                    from backend.agent.specialists.email_specialist import is_valid_email
                    if not is_valid_email(cur_to):
                        return SwarmPlan(
                            plan_type="direct",
                            provider_used="prefilter",
                            direct_response=f"I have added the message to the draft, sir. However, '{cur_to}' is not a complete email address with a domain. What is the recipient's full email address?",
                        )
                    return SwarmPlan(
                        plan_type="parallel",
                        provider_used="prefilter",
                        steps=[{
                            "agent": "email",
                            "action": "send_email",
                            "params": {
                                "to": cur_to,
                                "subject": pending_draft.get("subject", "A brief note"),
                                "body": merged_body,
                            }
                        }],
                    )
                else:
                    return SwarmPlan(
                        plan_type="direct",
                        provider_used="prefilter",
                        direct_response=f"I have added your message to the draft for {cur_to}, sir. Would you like me to dispatch the email now?",
                    )

            is_confirmation = any(
                re.search(rf"\b{w}\b", q_lower)
                for w in [
                    "yes", "yeah", "sure", "send it", "send", "go ahead", "dispatch",
                    "confirm", "looks good", "send that email", "shoot", "do it",
                ]
            ) and not any(w in q_lower for w in ["don't", "dont", "no", "cancel", "stop", "change"])
            if is_confirmation:
                from backend.agent.specialists.email_specialist import is_valid_email

                if not is_valid_email(cur_to):
                    logger.info(f"[Planner.PreFilter] Blocked dispatch to invalid recipient: '{cur_to}'")
                    return SwarmPlan(
                        plan_type="direct",
                        provider_used="prefilter",
                        direct_response=f"I cannot send the email yet, sir. '{cur_to}' is not a complete email address with a domain. What is the recipient's full email address?",
                    )

                logger.info("[Planner.PreFilter] User confirmed pending email draft -> email:send_email")
                return SwarmPlan(
                    plan_type="parallel",
                    provider_used="prefilter",
                    steps=[{
                        "agent": "email",
                        "action": "send_email",
                        "params": {
                            "to": cur_to,
                            "subject": pending_draft.get("subject", "A brief note"),
                            "body": pending_draft.get("body", ""),
                        }
                    }],
                )

            is_cancellation = any(
                re.search(rf"\b{w}\b", q_lower)
                for w in ["cancel", "don't send", "dont send", "no", "discard", "forget it", "never mind", "stop"]
            )
            if is_cancellation:
                logger.info("[Planner.PreFilter] User cancelled pending email draft")
                return SwarmPlan(
                    plan_type="direct",
                    provider_used="prefilter",
                    direct_response="Understood, sir. I have discarded the email draft.",
                )

        # 1. Multi-Turn Email Anaphora & Contextual Sender Lookup:
        active_email = session_context.get("active_email") if session_context else None
        is_who_sent_email = any(
            re.search(pat, q_lower)
            for pat in [
                r"\bwho sent (me )?(the|that) email\b",
                r"\bwho sent the email we were discussing\b",
                r"\bwho is (the|that) email from\b",
                r"\bwho was that email from\b",
                r"\bwho sent it\b",
            ]
        )
        if is_who_sent_email:
            if active_email and (active_email.get("sender_name") or active_email.get("sender")):
                sender_name = active_email.get("sender_name") or active_email.get("sender", "Unknown sender")
                sender_addr = active_email.get("sender", "")
                subject = active_email.get("subject", "")
                logger.info(f"[Planner.PreFilter] Resolving 'who sent the email' from active session context: {sender_name}")
                addr_info = f" ({sender_addr})" if sender_addr else ""
                subj_info = f" regarding '{subject}'" if subject else ""
                return SwarmPlan(
                    plan_type="direct",
                    provider_used="prefilter",
                    direct_response=f"The email we were discussing was sent by {sender_name}{addr_info}{subj_info}, sir.",
                )
            else:
                return SwarmPlan(
                    plan_type="direct",
                    provider_used="prefilter",
                    direct_response="Which email or conversation are you referring to, sir?",
                )

        # 2. Financial Overview, Balance & Transactions:
        is_financial_summary_query = bool(
            re.search(
                r"\b(how am i doing financially|how are (my|our) finances|financial (standing|status|health|summary|overview|position)|check (my )?finances|overall financial|how is my money|what is my net worth|what('s| is) my net worth)\b",
                q_lower,
            )
        )
        if is_financial_summary_query:
            logger.info("[Planner.PreFilter] Matched financial overview query -> finance:get_financial_summary")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "finance", "action": "get_financial_summary", "params": {}}],
            )

        is_balance_query = bool(
            re.search(
                r"\b(what('s| is) my (bank )?balance|check (my )?(bank )?balance|my account balance|how much money do i have|check balance|show (my )?balance)\b",
                q_lower,
            )
        )
        if is_balance_query:
            from backend.agent.normalizer import extract_bank_and_intent, resolve_bank_alias
            detected_bank, _ = extract_bank_and_intent(q_lower)
            acc_name = resolve_bank_alias(detected_bank) if detected_bank else None
            params = {"account_name": acc_name} if acc_name else {}
            logger.info(f"[Planner.PreFilter] Matched balance query -> finance:get_balance {params}")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "finance", "action": "get_balance", "params": params}],
            )

        is_txn_list_query = bool(
            re.search(
                r"\b(show|list|get|check|view)\s+(my\s+)?(recent\s+)?(transactions?|expenses?|spends?|spendings?|payments?)\b",
                q_lower,
            )
            or re.search(r"\b(recent\s+transactions?|recent\s+expenses?)\b", q_lower)
            and not any(w in q_lower for w in ["email", "emails", "inbox", "mail", "gmail", "task", "tasks"])
        )
        if is_txn_list_query:
            from backend.agent.normalizer import extract_bank_and_intent, resolve_bank_alias
            detected_bank, _ = extract_bank_and_intent(q_lower)
            acc_name = resolve_bank_alias(detected_bank) if detected_bank else None
            params = {"account_name": acc_name} if acc_name else {}
            logger.info(f"[Planner.PreFilter] Matched transactions list query -> finance:list_transactions {params}")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "finance", "action": "list_transactions", "params": params}],
            )

        # 3. Explicit Screen perception: Screen/desktop look/inspect/ocr
        has_screen_target = any(w in q_lower for w in ["screen", "monitor", "display", "desktop", "ide"])
        has_perception_verb = any(w in q_lower for w in ["look", "see", "read", "ocr", "check", "inspect"])
        if has_screen_target and has_perception_verb:
            act = "ocr_screen" if "ocr" in q_lower else "inspect_screen"
            logger.info(f"[Planner.PreFilter] Matched explicit screen query -> vision:{act}")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "vision", "action": act, "params": {"query": query}}],
            )

        # 4. Physical / Handheld / Webcam perception:
        is_handheld = any(w in q_lower for w in ["holding", "in my hand", "in my hands", "showing you", "in front of me", "am i holding"])
        is_doc = any(w in q_lower for w in ["receipt", "bill", "invoice", "document", "paper", "ticket", "business card", "label", "note", "letter", "prescription", "barcode"])
        has_camera_target = any(w in q_lower for w in ["camera", "webcam"])
        has_perception = any(w in q_lower for w in ["look", "see", "read", "ocr", "check", "inspect", "details of", "tell me about", "what does", "what is", "describe", "scan", "extract"])

        if (has_camera_target and has_perception) or (is_handheld and has_perception) or (is_doc and any(w in q_lower for w in ["read", "ocr", "details of", "inspect", "check", "scan", "what is", "tell me about"])):
            is_ocr = is_doc or any(w in q_lower for w in ["ocr", "read", "text", "say", "written", "words", "details of", "bill", "invoice", "number", "amount", "total"])
            act = "ocr_webcam" if is_ocr else "inspect_webcam"
            params: Dict[str, Any] = {"query": query}
            if is_doc:
                params["focus_hint"] = "Extract merchant/vendor, date, line items, prices, taxes, total amount, and payment details verbatim."
            logger.info(f"[Planner.PreFilter] Matched handheld/document vision query -> vision:{act} ({params})")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "vision", "action": act, "params": params}],
            )

        # 5. Inbox / Unread Emails check:
        is_unread_email_query = bool(
            re.search(
                r"\b(check|read|show|list|get|any|do i have|what are)\s+(my\s+)?(unread|new|latest|recent|inbox)?\s*(emails?|messages?|inbox)\b",
                q_lower,
            )
            or re.search(r"\b(unread|new)\s+emails?\b", q_lower)
            or re.search(r"\bcheck\s+(my\s+)?(emails?|inbox)\b", q_lower)
        ) and not any(w in q_lower for w in ["thread", "chain", "conversation with", "sent the", "send an email", "compose", "reply", "draft"])
        if is_unread_email_query:
            logger.info("[Planner.PreFilter] Matched unread/inbox email query -> email:list_unread_emails")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "email", "action": "list_unread_emails", "params": {}}],
            )

        # 5b. Search / Check Mobile Notifications (WhatsApp, Slack, Telegram, phone alerts)
        has_notif_word = (
            any(w in q_lower for w in [
                "notification", "notifications", "whatsapp alert", "phone alert", "mobile alert",
                "notification that", "notification from", "sent on whatsapp", "check whatsapp",
                "search whatsapp", "whatsapp message", "slack message", "telegram message",
                "check messages", "check my messages", "search notifications", "check notifications",
            ])
            or (any(app in q_lower for app in ["whatsapp", "slack", "telegram"]) and any(w in q_lower for w in ["check", "search", "find", "get", "read", "see", "any", "name"]))
        )
        if has_notif_word and not any(w in q_lower for w in ["screen", "monitor", "display"]):
            app_filter = None
            for app in ["whatsapp", "slack", "telegram", "gmail", "discord", "signal"]:
                if app in q_lower:
                    app_filter = app
                    break

            sender = None
            sender_match = re.search(r"(?:from|by|sent by)\s+([a-zA-Z\s]+?)(?:\s+on|\s+in|\s+about|\s+regarding|\?|$)", query, re.IGNORECASE)
            if not sender_match:
                sender_match = re.search(r"notification that\s+([a-zA-Z\s]+?)\s+sent", query, re.IGNORECASE)
            if sender_match:
                sender = sender_match.group(1).strip()

            logger.info(f"[Planner.PreFilter] Matched notification search query -> tasks:search_mobile_notifications (sender={sender}, app={app_filter})")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{
                    "agent": "tasks",
                    "action": "search_mobile_notifications",
                    "params": {
                        "query": query,
                        "sender": sender or "",
                        "app": app_filter,
                    },
                }],
            )

        # 5c. Task / Event Renaming, Updating, or Deleting:
        # Check compound queries first: e.g. "Remove the 8 o'clock event and rename the 9 o'clock event to AWS Workshop"
        m_compound_del_rename = re.search(
            r"\b(?:remove|delete|cancel)\s+(?:the\s+)?(?P<del_target>.+?)\s+and\s+(?:rename|change)\s+(?:the\s+)?(?P<ren_target>.+?)\s+(?:to|as)\s+[\"']?(?P<new_title>[^\"'\n\.]+)",
            query,
            re.IGNORECASE,
        )
        if m_compound_del_rename:
            del_t = m_compound_del_rename.group("del_target").strip()
            ren_t = m_compound_del_rename.group("ren_target").strip()
            new_t = m_compound_del_rename.group("new_title").strip()
            logger.info(f"[Planner.PreFilter] Matched compound remove & rename query -> tasks:delete_task ({del_t}) + tasks:update_task ({ren_t} -> {new_t})")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[
                    {"agent": "tasks", "action": "delete_task", "params": {"title": del_t}},
                    {"agent": "tasks", "action": "update_task", "params": {"query": ren_t, "new_title": new_t}},
                ],
            )

        # Single rename query: e.g. "Rename the 9 o'clock event to AWS Workshop", "Rename task X to Y"
        m_rename = re.search(
            r"\b(?:rename|change(?:\s+the\s+name\s+of)?|retitled?)\s+(?:the\s+)?(?P<target>.+?)\s+(?:to|as)\s+[\"']?(?P<new_title>[^\"'\n\.]+)",
            query,
            re.IGNORECASE,
        )
        if m_rename and not any(w in q_lower for w in ["file", "folder", "directory", "code", "variable", "branch"]):
            ren_t = m_rename.group("target").strip()
            new_t = m_rename.group("new_title").strip()
            logger.info(f"[Planner.PreFilter] Matched rename query -> tasks:update_task ({ren_t} -> {new_t})")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{
                    "agent": "tasks",
                    "action": "update_task",
                    "params": {
                        "query": ren_t,
                        "new_title": new_t,
                    },
                }],
            )

        # Single delete query: e.g. "Remove the 8 o'clock event", "delete the 8 o'clock event", "delete task buy milk"
        m_delete = re.search(
            r"\b(?:remove|delete|cancel)\s+(?:the\s+)?(?P<target>[^,\.]*?(?:event|meeting|task|reminder|\d{1,2}\s*o'?clock|\d{1,2}(?::\d{2})?\s*(?:am|pm)))(?:\s+from\s+(?:my\s+)?(?:calendar|schedule|agenda|tasks|reminders|list))?$",
            query,
            re.IGNORECASE,
        )
        if m_delete and not any(w in q_lower for w in ["file", "folder", "directory", "screen", "window", "device"]):
            del_t = m_delete.group("target").strip()
            logger.info(f"[Planner.PreFilter] Matched delete task/event query -> tasks:delete_task ({del_t})")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{
                    "agent": "tasks",
                    "action": "delete_task",
                    "params": {"title": del_t},
                }],
            )

        # 6. Network Device Discovery & Subnet Scan:
        is_network_scan_query = bool(
            re.search(
                r"\b(scan|detect|find|search)\s+(for\s+)?(the\s+)?(network|lan|subnet|wifi|edge|connected)?\s*(devices|nodes|hardware)\b",
                q_lower,
            )
            or re.search(r"\b(scan\s+(the\s+)?(network|subnet|lan|wifi)|detect\s+(network\s+)?devices)\b", q_lower)
        )
        if is_network_scan_query:
            logger.info("[Planner.PreFilter] Matched network scan query -> system:scan_network_devices")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "system", "action": "scan_network_devices", "params": {}}],
            )

        # 6b. Screen / Display Power Management (screen off, display off, sleep screen, wake screen):
        is_screen_off_query = bool(
            re.search(
                r"\b(turn\s+off|power\s+off|shut\s+off|switch\s+off|sleep|kill)\s+(the\s+)?(screen|display|monitor|screens|monitors)\b",
                q_lower,
            )
            or re.search(r"\b(screen|display|monitor)\s+(off|sleep)\b", q_lower)
            or re.search(r"\b(put\s+(the\s+)?(screen|display|monitor|device|system)\s+to\s+sleep)\b", q_lower)
        )
        if is_screen_off_query:
            logger.info("[Planner.PreFilter] Matched screen power off query -> system:set_screen_power (state=off)")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "system", "action": "set_screen_power", "params": {"state": "off"}}],
            )

        is_screen_on_query = bool(
            re.search(
                r"\b(turn\s+on|power\s+on|switch\s+on|wake|wake\s+up)\s+(the\s+)?(screen|display|monitor|screens|monitors)\b",
                q_lower,
            )
            or re.search(r"\b(screen|display|monitor)\s+on\b", q_lower)
        )
        if is_screen_on_query:
            logger.info("[Planner.PreFilter] Matched screen power on query -> system:set_screen_power (state=on)")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "system", "action": "set_screen_power", "params": {"state": "on"}}],
            )

        # 6c. Screen / Session Lock (lock screen, lock session, lock my pc):
        is_lock_query = bool(
            re.search(
                r"\b(lock\s+(the\s+)?(screen|session|display|pc|laptop|computer)|lock\s+my\s+(pc|laptop|computer|screen))\b",
                q_lower,
            )
            or q_lower.strip() in ("lock", "lock screen", "lock session", "lock pc")
        )
        if is_lock_query:
            logger.info("[Planner.PreFilter] Matched lock session query -> system:lock_session")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "system", "action": "lock_session", "params": {}}],
            )

        # 7. GitHub Repository Queries (my repos, recent projects on github):
        is_github_repo_query = bool(
            re.search(
                r"\b(github|git\s?hub)\b",
                q_lower,
            )
        ) and bool(
            re.search(
                r"\b(recent|latest|my|last|new|current)\s+(project|repo|repositor|code)\b",
                q_lower,
            )
            or re.search(
                r"\b(list|show|what|check)\s+(are\s+)?(my\s+)?(projects?|repos?|repositor)\b",
                q_lower,
            )
        )
        if is_github_repo_query:
            logger.info("[Planner.PreFilter] Matched GitHub repo listing query -> github:list_user_repos")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "github", "action": "list_user_repos", "params": {"limit": 5}}],
            )

        # 8. Fast Email Drafting & Composition:
        m_draft = re.search(
            r"\b(?:write|draft|compose)\s+(?:an?\s+)?emails?\s+to\s+([^\s,]+@[^\s,]+|[a-zA-Z0-9._%+-]+)\s+(?:saying|about|with\s+(?:body|text|message)?)\s+(.+)",
            query,
            flags=re.IGNORECASE,
        )
        if m_draft:
            recipient = m_draft.group(1).strip()
            raw_body = m_draft.group(2).strip()
            logger.info(f"[Planner.PreFilter] Matched direct email drafting query -> to: '{recipient}'")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{
                    "agent": "email",
                    "action": "draft_email",
                    "params": {"to": recipient, "subject": "A brief note", "body": raw_body},
                }],
            )

        # 9. Spotify Playlist Listing Queries (0-token fast path):
        is_list_playlists_query = bool(
            re.search(
                r"\b(?:what|list|show|get|tell\s+me|display|which)\b.*\bplaylists?\b",
                q_lower,
            )
            or re.search(r"\bplaylists?\s+(?:do\s+i\s+have|i\s+have|in\s+my\s+library|on\s+(?:my\s+)?spotify)\b", q_lower)
            or re.search(r"^(?:my\s+)?playlists?$", q_lower.strip())
        ) and not any(w in q_lower for w in ["play ", "start ", "shuffle ", "queue "])
        if is_list_playlists_query:
            logger.info("[Planner.PreFilter] Matched list playlists query -> media:list_playlists")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "media", "action": "list_playlists", "params": {"limit": 25}}],
            )

        # 10. Direct Playlist Playback: "play [my] playlist <name>", "play <name> playlist"
        m_play_pl = (
            re.search(r"\b(?:play|start|shuffle)\s+(?:my\s+)?playlist\s+([a-zA-Z0-9\s!_'-]+?)(?:\s+on\s+spotify)?$", q_lower)
            or re.search(r"\b(?:play|start|shuffle)\s+(?:my\s+)?([a-zA-Z0-9\s!_'-]+?)\s+playlist(?:\s+on\s+spotify)?$", q_lower)
        )
        if m_play_pl and not any(w in q_lower for w in ["what", "list", "show", "tell me", "which"]):
            target_pl = m_play_pl.group(1).strip()
            if target_pl:
                logger.info(f"[Planner.PreFilter] Matched direct playlist playback -> media:play_playlist('{target_pl}')")
                return SwarmPlan(
                    plan_type="parallel",
                    provider_used="prefilter",
                    steps=[{"agent": "media", "action": "play_playlist", "params": {"name": target_pl}}],
                )

        # ── TIER 2: LOCAL SEMANTIC INTENT ROUTER (~10ms CPU, 0 tokens) ────────
        intent, conf, proto = self.semantic_router.classify(query)

        if intent == SemanticIntent.HANDHELD_OBJECT_RESEARCH:
            logger.info(f"[Planner.PreFilter] Semantic match: HANDHELD_OBJECT_RESEARCH (conf={conf:.2f}, proto='{proto}')")
            is_document_read = any(
                w in q_lower for w in [
                    "receipt", "bill", "invoice", "document", "letter", "note", "paper",
                    "what does it say", "what does this say", "read it", "read this",
                    "read what", "transcribe", "text on", "details of"
                ]
            ) and not any(
                w in q_lower for w in [
                    "author", "rating", "review", "price", "buy", "online", "who wrote",
                    "other books", "worth", "reviews", "google"
                ]
            )
            if is_document_read:
                return SwarmPlan(
                    plan_type="parallel",
                    provider_used="prefilter",
                    steps=[
                        {
                            "agent": "vision",
                            "action": "ocr_webcam",
                            "params": {
                                "query": query,
                                "focus_hint": "Extract merchant/vendor, date, line items, prices, taxes, total amount, and payment details verbatim.",
                            },
                        }
                    ],
                )

            # Preserve user secondary questions or specific attributes (e.g. "and tell the best book", "sugar content", "calories")
            secondary_hint = ""
            for conj in [" and ", " also ", " plus ", " then ", ", "]:
                if conj in query.lower():
                    parts = re.split(rf"{conj}", query, flags=re.IGNORECASE)
                    for p in parts[1:]:
                        clean_p = p.strip()
                        if any(w in clean_p.lower() for w in ["best", "other", "author", "similar", "rating", "review", "sequel", "movie", "synopsis", "summary", "price", "more", "sugar", "calorie", "nutrition", "ingredient"]):
                            secondary_hint = f" {clean_p}"
                            break
                    if secondary_hint:
                        break

            if not secondary_hint:
                m_attr = re.search(
                    r"\b(?:what is|tell me|check|find|how many|what are)\s+(?:the\s+)?([a-zA-Z0-9\s]+?)\s+(?:of|for|in|about)\s+(?:what|the\s+item|this|the\s+product|the\s+book)\b",
                    query,
                    flags=re.IGNORECASE,
                )
                if m_attr:
                    attr_name = m_attr.group(1).strip()
                    if attr_name and not any(w in attr_name.lower() for w in ["what", "this", "name"]):
                        secondary_hint = f" {attr_name}"

            is_nutrition_or_visual = any(w in q_lower for w in ["sugar", "calorie", "nutrition", "carbs", "ingredient", "fat", "protein", "healthy", "what is this", "what am i holding"])
            first_action = "inspect_webcam" if is_nutrition_or_visual else "ocr_webcam"
            first_params = (
                {"query": f"Identify the product or item shown in the webcam and describe its brand, type, and details: {query}"}
                if is_nutrition_or_visual
                else {"focus_hint": "Extract all visible text: title, author, brand, subtitle, or any identifying label."}
            )

            search_query_tmpl = f"$step_1.description{secondary_hint}" if first_action == "inspect_webcam" else f"$step_1.extracted_text{secondary_hint}"
            return SwarmPlan(
                plan_type="sequential",
                provider_used="prefilter",
                steps=[
                    {"agent": "vision", "action": first_action, "params": first_params},
                    {"agent": "research", "action": "web_search", "params": {"query": search_query_tmpl}},
                ],
            )

        if intent == SemanticIntent.VERIFY_RESEARCH:
            clean_sq = re.sub(
                r"^(please\s+)?(can you\s+)?(are you sure[,.]?\s+try|try (again|researching|to search)|research (it|this|more|properly|again)|nah that ain't it|that's wrong|wrong|no try again)\s*",
                "",
                query,
                flags=re.IGNORECASE,
            ).strip()
            if not clean_sq or len(clean_sq) < 3:
                if session_context and session_context.get("active_visual"):
                    clean_sq = session_context["active_visual"].get("text", query)[:300]
                else:
                    clean_sq = query
            logger.info(f"[Planner.PreFilter] Semantic match: VERIFY_RESEARCH (conf={conf:.2f}) -> fresh research for: '{clean_sq}'")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "research", "action": "web_search", "params": {"query": clean_sq}}],
            )

        if intent == SemanticIntent.EMAIL_THREAD:
            m_target = re.search(r"\b(?:conversation|thread|chain|emails?|messages?)\s+(?:with|from|regarding|about)\s+([a-zA-Z0-9_\s]+)", q_lower)
            target_query = None
            if m_target:
                raw_target = m_target.group(1).strip()
                clean_target = re.sub(r"^(about|regarding|with|from)\s+", "", raw_target).strip()
                target_query = clean_target or raw_target

            tid = (active_email.get("thread_id") or active_email.get("id")) if (active_email and not target_query) else None
            eid = active_email.get("id") if (active_email and not target_query) else None

            step_params: Dict[str, Any] = {}
            if tid:
                step_params["thread_id"] = tid
            if eid:
                step_params["email_id"] = eid
            if target_query:
                step_params["query"] = target_query
            if not step_params:
                step_params = {"query": query}

            logger.info(f"[Planner.PreFilter] Semantic match: EMAIL_THREAD (conf={conf:.2f}) -> email:read_thread")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "email", "action": "read_thread", "params": step_params}],
            )

        if intent == SemanticIntent.UNREAD_EMAILS:
            logger.info(f"[Planner.PreFilter] Semantic match: UNREAD_EMAILS (conf={conf:.2f}) -> email:list_unread_emails")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "email", "action": "list_unread_emails", "params": {}}],
            )

        is_direct_song_movie = (
            any(w in q_lower for w in ["what song", "what track", "playing right now", "current song", "this track"])
            and any(w in q_lower for w in ["movie", "film", "album", "who sang", "singer", "actor", "from"])
        )
        if intent == SemanticIntent.SONG_ORIGIN or is_direct_song_movie:
            logger.info(f"[Planner.PreFilter] Semantic match: SONG_ORIGIN (conf={conf:.2f}) -> sequential media + research")
            return SwarmPlan(
                plan_type="sequential",
                provider_used="prefilter",
                steps=[
                    {"agent": "media", "action": "get_playback_status", "params": {}},
                    {"agent": "research", "action": "web_search", "params": {"query": "$step_1.track movie"}},
                ],
            )

        if intent == SemanticIntent.DAILY_AGENDA:
            logger.info(f"[Planner.PreFilter] Semantic match: DAILY_AGENDA (conf={conf:.2f}) -> tasks:get_daily_agenda")
            target_date = "today"
            if "next week" in q_lower:
                target_date = "next week"
            elif "this week" in q_lower:
                target_date = "this week"
            elif "tomorrow" in q_lower:
                target_date = "tomorrow"
            elif "yesterday" in q_lower:
                target_date = "yesterday"
            else:
                for day_name in ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]:
                    if day_name in q_lower:
                        target_date = f"next {day_name}" if "next" in q_lower else day_name
                        break

            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "tasks", "action": "get_daily_agenda", "params": {"date": target_date, "query": query}}],
            )

        if intent == SemanticIntent.FINANCE_BALANCE:
            logger.info(f"[Planner.PreFilter] Semantic match: FINANCE_BALANCE (conf={conf:.2f}) -> finance:get_balance")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "finance", "action": "get_balance", "params": {}}],
            )

        if intent == SemanticIntent.SYSTEM_STATUS:
            logger.info(f"[Planner.PreFilter] Semantic match: SYSTEM_STATUS (conf={conf:.2f}) -> system:get_system_vitals")
            steps = [{"agent": "system", "action": "get_system_vitals", "params": {}}]
            if any(w in q_lower for w in ["cluster", "network", "node", "nodes", "subnet", "sweep"]):
                steps.append({"agent": "system", "action": "scan_network_devices", "params": {}})
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=steps,
            )

        if intent == SemanticIntent.MOBILE_NOTIFICATIONS:
            logger.info(f"[Planner.PreFilter] Semantic match: MOBILE_NOTIFICATIONS (conf={conf:.2f}) -> tasks:list_mobile_notifications")
            unread_only = "unread" in q_lower or "new" in q_lower
            app_filter = None
            for app in ["whatsapp", "slack", "telegram", "gmail", "discord"]:
                if app in q_lower:
                    app_filter = app
                    break
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "tasks", "action": "list_mobile_notifications", "params": {"unread_only": unread_only, "app": app_filter}}],
            )

        if intent == SemanticIntent.BATTERY_STATUS:
            logger.info(f"[Planner.PreFilter] Semantic match: BATTERY_STATUS (conf={conf:.2f}) -> system:check_battery_status")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "system", "action": "check_battery_status", "params": {}}],
            )

        # ── WEATHER PREFILTER ─────────────────────────────────────────────────
        def _extract_weather_location(query_text: str) -> Optional[str]:
            q_clean = query_text.rstrip("?.! ")
            m = re.search(
                r"\b(?:in|at|for|around)\s+([a-zA-Z\s,]+?)(?:\s+(?:tomorrow\s+(?:morning|afternoon|evening|night)|tomorrow|today|tonight|yesterday|this weekend|next week|right now|currently|now|this evening|this morning|this afternoon))?$",
                q_clean,
                re.IGNORECASE,
            )
            if m:
                cand = m.group(1).strip(", ")
                if cand.lower() not in (
                    "the morning", "the afternoon", "the evening", "the night",
                    "the week", "the weekend", "a few days", "the next few days", "me", "us"
                ):
                    return cand.title()
            return None

        # Rain / storm / umbrella check
        is_rain_check = any(p in q_lower for p in [
            "will it rain", "going to rain", "is it raining", "rain today", "rain tomorrow",
            "need an umbrella", "carry an umbrella", "umbrella", "bring a raincoat",
            "chance of rain", "precipitation", "will it storm", "thunderstorm today",
        ])
        if is_rain_check:
            location = _extract_weather_location(query)
            logger.info(f"[Planner.PreFilter] Rain check detected -> weather:check_rain (location={location})")
            if not registry or registry.get("weather"):
                return SwarmPlan(
                    plan_type="parallel",
                    provider_used="prefilter",
                    steps=[{"agent": "weather", "action": "check_rain", "params": {"location": location, "hours_ahead": 6} if location else {"hours_ahead": 6}}],
                )
            elif registry.get("research"):
                return SwarmPlan(
                    plan_type="parallel",
                    provider_used="prefilter",
                    steps=[{"agent": "research", "action": "web_search", "params": {"query": f"rain forecast {location}" if location else "will it rain today"}}],
                )

        # Weather forecast (future weather: tomorrow, next week, weekend, forecast, going to be, will it be)
        is_forecast = (
            any(p in q_lower for p in [
                "weather forecast", "forecast for", "weather this week", "weather next",
                "tomorrow's weather", "what will the weather be", "weather for the next",
                "tomorrow", "day after tomorrow", "this weekend", "next week", "forecast",
                "going to be", "will the weather be", "will it be", "upcoming weather",
            ])
            and any(w in q_lower for w in ["weather", "temperature", "forecast", "climate", "conditions", "hot", "cold", "sunny", "rainy", "warm"])
        )
        if is_forecast:
            location = _extract_weather_location(query)
            days = 3
            days_match = re.search(r"(\d+)\s*days?", q_lower)
            if days_match:
                days = int(days_match.group(1))
            elif "tomorrow" in q_lower:
                days = 2
            elif "weekend" in q_lower or "week" in q_lower:
                days = 5

            logger.info(f"[Planner.PreFilter] Forecast detected -> weather:get_weather_forecast (location={location}, days={days})")
            if not registry or registry.get("weather"):
                return SwarmPlan(
                    plan_type="parallel",
                    provider_used="prefilter",
                    steps=[{"agent": "weather", "action": "get_weather_forecast", "params": {"location": location, "days": days} if location else {"days": days}}],
                )
            elif registry.get("research"):
                return SwarmPlan(
                    plan_type="parallel",
                    provider_used="prefilter",
                    steps=[{"agent": "research", "action": "web_search", "params": {"query": f"{days} day weather forecast for {location}" if location else "weather forecast"}}],
                )

        # Current weather / conditions
        is_current_weather = any(p in q_lower for p in [
            "what's the weather", "what is the weather", "how's the weather",
            "current weather", "weather right now", "weather today",
            "is it hot", "is it cold", "temperature outside", "weather outside",
            "weather in", "how's it outside", "temperature in", "temperature at",
        ])
        if is_current_weather:
            location = _extract_weather_location(query)
            logger.info(f"[Planner.PreFilter] Weather inquiry detected -> weather:get_current_weather (location={location})")
            if not registry or registry.get("weather"):
                return SwarmPlan(
                    plan_type="parallel",
                    provider_used="prefilter",
                    steps=[{"agent": "weather", "action": "get_current_weather", "params": {"location": location} if location else {}}],
                )
            elif registry.get("research"):
                return SwarmPlan(
                    plan_type="parallel",
                    provider_used="prefilter",
                    steps=[{"agent": "research", "action": "web_search", "params": {"query": f"weather in {location}" if location else "current weather"}}],
                )

        # ── CONVERSATION PREFILTER ────────────────────────────────────────────
        # Greetings and simple chit-chat
        is_greeting = any(p in q_lower for p in [
            "good morning alfred", "good afternoon alfred", "good evening alfred",
            "hey alfred", "hello alfred", "hi alfred",
        ])
        if is_greeting:
            logger.info("[Planner.PreFilter] Greeting detected -> conversation:chit_chat")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "conversation", "action": "chit_chat", "params": {"query": query}}],
            )

        is_how_are_you = bool(re.search(
            r"\b(how are you|how are you doing|how do you feel|how's it going|you doing|you alright)\b", q_lower
        ))
        if is_how_are_you:
            logger.info("[Planner.PreFilter] How-are-you detected -> conversation:chit_chat")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "conversation", "action": "chit_chat", "params": {"query": query}}],
            )

        # Dialogue recall / history queries
        is_recall = any(p in q_lower for p in [
            "what have we worked on", "what did we work on",
            "what did we talk about", "what have we discussed",
            "what did we discuss", "remind me of our conversations",
            "recall our previous", "what did we do last", "recap of our",
            "what have we been working on",
        ])
        if is_recall:
            logger.info("[Planner.PreFilter] Conversation recall detected -> conversation:recall_conversations")
            return SwarmPlan(
                plan_type="parallel",
                provider_used="prefilter",
                steps=[{"agent": "conversation", "action": "recall_conversations", "params": {"query": query, "time_range": "week"}}],
            )

        return None

    def _select_candidate_specialists(
        self,
        query: str,
        session_context: Optional[Dict[str, Any]] = None,
    ) -> List[str]:
        """Selects the 2-4 candidate specialists relevant to the user query and active context."""
        q_lower = query.lower()
        candidates: set[str] = set()

        domain_keywords = {
            "media": ["play", "song", "music", "track", "spotify", "artist", "album", "volume", "pause", "resume", "listen", "soundtrack", "lofi", "playlist", "playlists"],
            "tasks": [
                "task", "todo", "reminder", "remind", "calendar", "event", "meeting", "agenda", "schedule", "appointment",
                "notification", "notifications", "whatsapp", "slack", "telegram", "sms", "alert", "alerts",
            ],
            "email": ["email", "mail", "inbox", "thread", "message", "sender", "unread", "draft", "rohit", "arpit", "hemanshu"],
            "vision": ["see", "look", "watch", "camera", "webcam", "screen", "display", "monitor", "holding", "read", "ocr", "terminal", "window"],
            "github": ["repo", "repository", "git", "github", "commit", "branch", "pr", "pull request", "issue", "clone", "code"],
            "finance": [
                "balance", "bank", "money", "rupees", "inr", "expense", "expenses", "spent", "spending", "split", "debt", "debts",
                "owe", "owes", "transaction", "transactions", "financial", "financially", "finances", "wealth", "funds", "ledger",
                "atm", "cash", "saraswat", "sarasworth", "sbi", "union bank", "hdfc", "icici", "savings", "salary", "net worth",
                "account", "accounts",
            ],
            "memory": ["remember", "forget", "recall", "memorize", "preference", "profile", "what do you know about me"],
            "system": ["volume", "battery", "cpu", "ram", "specs", "brightness", "bluetooth", "wifi", "host", "system", "cluster", "vitals", "hardware", "report"],
            "crawl": ["crawl", "scrape", "documentation", "scrape page", "docs for"],
            "weather": [
                "weather", "temperature", "rain", "raining", "sunny", "cloudy", "overcast", "fog", "foggy",
                "humidity", "wind", "storm", "thunderstorm", "drizzle", "umbrella", "forecast", "climate",
                "how hot", "how cold", "will it rain", "should i carry", "uv index", "feels like",
                "precipitation", "snowfall", "celsius", "degree",
            ],
            "conversation": [
                "how are you", "how are you doing", "how do you feel", "good morning alfred",
                "good afternoon alfred", "good evening alfred", "what have we", "what did we",
                "what have we worked on", "what did we talk about", "what did we discuss",
                "tell me about what", "remind me of", "chit chat", "how's it going",
                "what do you think", "catch up", "check in",
            ],
        }

        for domain, kws in domain_keywords.items():
            if any(kw in q_lower for kw in kws):
                candidates.add(domain)

        # Retain active context specialists
        if session_context:
            if session_context.get("active_email"):
                candidates.add("email")
            if session_context.get("active_track"):
                candidates.add("media")
            if session_context.get("active_repo"):
                candidates.add("github")
            if session_context.get("active_task"):
                candidates.add("tasks")
            if session_context.get("active_visual"):
                candidates.add("vision")

        # Always include research as fallback
        candidates.add("research")

        # If too few candidates matched, include common desk specialists
        if len(candidates) <= 1:
            candidates.update(["media", "tasks", "vision"])

        return list(candidates)

    async def create_plan(
        self,
        query: str,
        registry: SpecialistRegistry,
        history: Optional[List[Dict[str, str]]] = None,
        session_context: Optional[Dict[str, Any]] = None,
    ) -> Tuple[SwarmPlan, float]:
        """Stage 1: Generates an execution plan from the user query with conversation context."""
        # ── Deterministic Pre-Filter (<1ms) ──────────────────────────────────
        prefilter_plan = self._check_deterministic_prefilter(query, session_context, registry=registry)
        if prefilter_plan is not None:
            prefilter_plan.provider_used = "prefilter"
            logger.info("[Planner] Plan generated via deterministic pre-filter (0ms, provider: prefilter)")
            return prefilter_plan, 0.0

        candidate_specialists = self._select_candidate_specialists(query, session_context)
        capabilities = registry.get_capabilities_prompt(compact=True, specialist_names=candidate_specialists)
        now_dt = datetime.datetime.now().astimezone()
        current_datetime = now_dt.strftime("%A, %B %d, %Y, %I:%M %p %Z")
        current_day = now_dt.strftime("%A")
        system_prompt = PLANNER_SYSTEM_PROMPT.format(
            capabilities=capabilities,
            current_datetime=current_datetime,
            current_day=current_day,
        )

        messages = [
            {"role": "system", "content": system_prompt},
        ]

        # Inject active session context (holding active email, track, repo, task, visual, and dynamic entities)
        if session_context:
            context_lines = []
            active_email = session_context.get("active_email")
            if active_email:
                context_lines.append(
                    f"Active Email: ID='{active_email.get('id')}', ThreadID='{active_email.get('thread_id')}', "
                    f"Sender='{active_email.get('sender_name')} <{active_email.get('sender')}>', "
                    f"Subject='{active_email.get('subject')}'"
                )
            active_track = session_context.get("active_track")
            if active_track:
                context_lines.append(
                    f"Active Music Track: '{active_track.get('track')}' by {active_track.get('artist')} "
                    f"from album/film '{active_track.get('album')}'"
                )
            active_repo = session_context.get("active_repo")
            if active_repo:
                context_lines.append(f"Active GitHub Repo: '{active_repo.get('repo')}'")
            active_task = session_context.get("active_task")
            if active_task:
                context_lines.append(f"Active Task: '{active_task.get('title')}'")
            # Surface what Alfred just saw/read via camera or screen OCR
            active_visual = session_context.get("active_visual")
            if active_visual:
                src = active_visual.get("source", "camera")
                txt = active_visual.get("text", "")[:300]
                context_lines.append(f"Last Visual Observation ({src}): {txt}")

            # Surface active proactive staged actions so the planner can adopt and execute them
            active_staged = action_queue.get_active_actions()
            if active_staged:
                for a in active_staged:
                    evidence_src = a.raw_evidence.get("sender") or a.raw_evidence.get("source_title") or a.raw_evidence.get("app_name") or ""
                    evidence_msg = a.raw_evidence.get("message") or a.raw_evidence.get("raw_text") or a.raw_evidence.get("text") or ""
                    context_lines.append(
                        f"Active Proactive Staged Action: [ID: {a.id}] Domain='{a.domain}', Action='{a.action}', "
                        f"Target='{a.verbatim_text}', Params={json.dumps(a.params)}, "
                        f"Evidence=from '{evidence_src}': '{evidence_msg[:120]}'"
                    )

            if context_lines:
                messages.append({
                    "role": "system",
                    "content": "ACTIVE SESSION CONTEXT (retained across turns):\n" + "\n".join(context_lines),
                })

        # Inject recent dialogue history purely as reference context (NOT separate user messages)
        # to prevent fast LLM planners from confusing past user turns with current tasks.
        if history:
            hist_lines = []
            for turn in history[-4:]:
                r_label = "User" if turn.get("role") == "user" else "Alfred"
                c_text = turn.get("content", "").strip()
                if c_text:
                    hist_lines.append(f"{r_label}: {c_text}")
            if hist_lines:
                messages.append({
                    "role": "system",
                    "content": (
                        "RECENT CONVERSATION HISTORY (REFERENCE ONLY — DO NOT RE-EXECUTE COMPLETED REQUESTS):\n"
                        + "\n".join(hist_lines)
                    ),
                })

        messages.append({
            "role": "user",
            "content": f"CURRENT USER QUERY TO PLAN FOR (generate plan steps ONLY for this inquiry):\n\"{query}\"",
        })

        plan_data, elapsed_ms = await self.llm.generate_json(messages, temperature=0.1)

        try:
            plan = SwarmPlan(**plan_data)
            if plan.steps and plan.plan_type == "direct":
                plan.plan_type = "parallel"
            plan.provider_used = getattr(self.llm, "last_provider_used", "llm")
        except Exception as e:
            logger.warning(f"[Planner] Plan parsing fallback: {e}. Defaulting to direct.")
            plan = SwarmPlan(plan_type="direct", direct_response="How may I be of service, sir?", provider_used="fallback")

        # ── Post-LLM Task / Reminder / Event Title Normalizer & Safety Net ──
        for step in plan.steps:
            if step.get("agent") == "tasks":
                act_name = str(step.get("action", "")).lower().strip()
                if act_name in (
                    "add_task", "set_reminder", "schedule_event",
                    "create_task", "add_reminder", "create_event", "schedule_meeting", "new_task", "add", "reminder"
                ):
                    params = step.get("params", {})
                    extracted_frag = (
                        params.get("reminder")
                        or params.get("title")
                        or params.get("summary")
                        or params.get("task")
                        or params.get("text")
                        or query
                    )
                    action_info = build_action(query, str(extracted_frag))
                    time_anchor = params.get("time") or params.get("start_time") or action_info.time_phrase or "today"

                    if action_info.action_type == "reminder":
                        step["action"] = "set_reminder"
                        step["params"] = {
                            "reminder": action_info.title,
                            "time": time_anchor,
                            "priority": params.get("priority", "normal"),
                        }
                    elif action_info.action_type == "event":
                        step["action"] = "schedule_event"
                        step["params"] = {
                            "summary": action_info.title,
                            "start_time": time_anchor,
                            "end_time": params.get("end_time"),
                            "location": params.get("location", ""),
                            "description": params.get("description", ""),
                        }
                    else:  # task
                        step["action"] = "add_task"
                        step["params"] = {
                            "title": action_info.title,
                            "priority": params.get("priority", "normal"),
                            "time": time_anchor if time_anchor != "today" else None,
                        }
                elif act_name in (
                    "update_task", "rename_task", "reschedule_task", "edit_task",
                    "update_event", "rename_event", "reschedule_event", "modify_task",
                ):
                    step["action"] = "update_task"
                elif act_name in (
                    "delete_task", "remove_task", "delete_reminder", "remove_reminder",
                    "delete_event", "remove_event", "cancel_event", "delete",
                ):
                    step["action"] = "delete_task"

        # ── Post-LLM Personal Correspondence vs Web Search Disambiguation ──
        q_lower = query.lower()
        is_personal_inbox_query = any(kw in q_lower for kw in [
            "heard from", "heard back from", "hear back from", "email from", "emails from",
            "received from", "got an email from", "any message from", "messages from",
            "any mail from", "did i hear from", "did they email", "reply from", "replied to",
            "check my email", "check my inbox", "look in my email", "look in my inbox",
        ])

        if is_personal_inbox_query and not any(s.get("agent") == "email" for s in plan.steps):
            # Extract sender or topic target
            target_match = re.search(
                r"\b(?:from|about|regarding)\s+([a-zA-Z0-9_\s]+?)(?:\s+(?:regarding|about|status)|$)",
                query,
                re.IGNORECASE,
            )
            target_term = target_match.group(1).strip() if target_match else query
            logger.info(f"[Planner] Routing personal correspondence query '{query}' to email:search_emails for '{target_term}'")
            plan = SwarmPlan(
                plan_type="parallel",
                provider_used=getattr(self.llm, "last_provider_used", "llm"),
                steps=[{"agent": "email", "action": "search_emails", "params": {"query": target_term}}],
            )
            return plan, elapsed_ms

        # ── Post-LLM Factual & Search Guardrails ─────────────────────────────
        # If the LLM returned a direct conversational response for an explicit search or
        # realtime query, enforce an external research step to prevent hallucination.
        is_explicit_search = any(kw in q_lower for kw in [
            "search for", "search the web", "search web", "google", "look up", "lookup", "find information", "find out about"
        ])
        is_realtime_data = any(kw in q_lower for kw in [
            "weather in", "weather today", "forecast", "latest news", "news about", "who won the", "score of"
        ])
        is_media_trivia = not is_personal_inbox_query and any(kw in q_lower for kw in [
            "what movie is", "which movie is", "what film is", "which film is", "who directed", "who starred in",
            "who acted in", "who wrote the song", "who sang the song", "who is the director of", "who wrote",
            "release date of", "when was", "when did", "box office of"
        ])
        is_entity_lookup = any(
            re.search(rf"\b{re.escape(prefix)}\b", q_lower)
            for prefix in [
                "who is", "who was", "where is", "what is the capital of", "what is the net worth of",
                "who invented", "who discovered", "what year was", "what year did"
            ]
        )
        is_open_research = bool(
            re.search(r"\b(tell me (more )?about|what can you tell me about|more about|explain|describe|summarize|summary of|overview of|details? (about|on|of)|info (about|on)|information (about|on))\b", q_lower)
        )
        is_verify_request = bool(
            re.search(
                r"\b(are you sure|no[,.]?\s+try|nope[,.]?\s+try|wrong[,.]?\s+try|incorrect[,.]?\s+try"
                r"|try (again|researching|to search|looking it up|harder|properly)"
                r"|research (it|this|more|properly|again|better)"
                r"|double.?check|verify (this|that|it)"
                r"|look it up|check again|search (again|properly|better|more carefully)"
                r"|that('s| is) (wrong|incorrect|not right)"
                r"|you('re| are) (wrong|incorrect|hallucinating|making (it|this) up))\b",
                q_lower,
            )
        )

        if is_explicit_search or is_realtime_data or is_media_trivia or is_entity_lookup or is_open_research or is_verify_request:
            needs_override = (
                is_verify_request
                or plan.plan_type == "direct"
                or not any(s.get("agent") == "research" for s in plan.steps)
            )
            if needs_override:
                logger.info(f"[Planner] Enforcing research step for factual/verify query: '{query}'")
                clean_sq = re.sub(
                    r"^(please\s+)?(can you\s+)?(search\s+for|google|look\s+up|search\s+the\s+web\s+for|search\s+web\s+for|find\s+out\s+about|tell me (more )?about|what can you tell me about|are you sure[,.]?\s+try|try (again|researching|to search)|research (it|this|more|properly|again))\s+",
                    "",
                    query,
                    flags=re.IGNORECASE,
                ).strip()

                # Anaphora resolution: if clean_sq is a bare pronoun or generic noun
                # (e.g. "the book", "it", "this", "that movie") resolve it to the actual
                # visual observation from the previous turn (what Alfred just saw/OCR'd).
                _is_anaphoric = bool(re.fullmatch(
                    r"(the\s+)?(book|novel|movie|film|show|article|document|item|thing|object|it|this|that|them)(\s+(book|novel|movie|film|show))?",
                    clean_sq.strip(),
                    re.IGNORECASE,
                ))
                if _is_anaphoric and session_context:
                    active_visual = session_context.get("active_visual")
                    if active_visual and active_visual.get("text"):
                        logger.info("[Planner] Resolving anaphoric research query from active_visual context.")
                        clean_sq = active_visual["text"][:300]

                if not clean_sq or len(clean_sq) < 3:
                    clean_sq = query
                plan = SwarmPlan(
                    plan_type="parallel",
                    steps=[{"agent": "research", "action": "web_search", "params": {"query": clean_sq}}],
                )

        return plan, elapsed_ms

    async def execute_plan(
        self,
        plan: SwarmPlan,
        registry: SpecialistRegistry,
        context: Optional[Dict[str, Any]] = None,
    ) -> ExecutionResult:
        """Stage 2: Executes the plan across the registered specialist swarm."""
        t0 = time.perf_counter()

        if plan.plan_type == "direct" or not plan.steps:
            return ExecutionResult(
                plan_type="direct",
                direct_response=plan.direct_response,
                specialist_results=[],
                execution_latency_ms=(time.perf_counter() - t0) * 1000,
                provider_used=plan.provider_used,
            )

        # ── Parallel Execution (Independent Steps) ───────────────────────────
        if plan.plan_type == "parallel":
            tasks = [
                registry.execute_action(
                    agent_name=step.get("agent", ""),
                    action=step.get("action", ""),
                    params=step.get("params", {}),
                    context=context,
                )
                for step in plan.steps
            ]
            results = await asyncio.gather(*tasks, return_exceptions=False)
            exec_ms = (time.perf_counter() - t0) * 1000
            return ExecutionResult(
                plan_type="parallel",
                specialist_results=list(results),
                execution_latency_ms=exec_ms,
                provider_used=plan.provider_used,
            )

        # ── Sequential Execution (Chained Steps with Flexible Variable Interpolation) ──
        results: List[SpecialistResult] = []
        step_outputs: Dict[str, Any] = {}

        for idx, step in enumerate(plan.steps, start=1):
            agent_name = step.get("agent", "")
            action = step.get("action", "")
            params = step.get("params", {}).copy()

            # Dynamic variable interpolation (e.g. "$step_1.track movie", "$step_1.title", "$step_1.emails[0].id", "$step_1.result.top_result")
            def _resolve_step_var(step_num: str, prop_path: Optional[str]) -> Any:
                ref_step = f"step_{step_num}"
                if ref_step not in step_outputs and step_num == "0" and "step_1" in step_outputs:
                    ref_step = "step_1"
                curr = step_outputs.get(ref_step, {})
                if not prop_path:
                    return curr

                # Clean tokens from path: e.g. "emails[0].id", "result.top_result", "[0].id", "track"
                tokens = re.findall(r"[a-zA-Z0-9_-]+", prop_path)
                for tok in tokens:
                    if isinstance(curr, dict):
                        # Skip wrapper keys if present in path but not in curr
                        if tok.lower() in ("result", "data", "task", "email", "track", "repo", "item", "record") and tok not in curr and tok.lower() not in curr:
                            continue

                        # Direct key match (exact or case-insensitive)
                        matched_key = next((k for k in curr if k.lower() == tok.lower()), None)
                        if matched_key is not None:
                            curr = curr[matched_key]
                        elif tok.isdigit() and len(curr) > int(tok):
                            curr = curr.get(int(tok), curr.get(tok))
                        else:
                            # Auto-unwrap: if dict contains non-empty lists, search inside the first list
                            unwrapped = False
                            list_keys = [k for k, val in curr.items() if isinstance(val, list) and val]
                            for lk in list_keys:
                                sublist = curr[lk]
                                if tok.isdigit() and int(tok) < len(sublist):
                                    curr = sublist[int(tok)]
                                    unwrapped = True
                                    break
                                elif isinstance(sublist[0], dict):
                                    sub_matched_key = next((k for k in sublist[0] if k.lower() == tok.lower()), None)
                                    if sub_matched_key is not None:
                                        curr = sublist[0][sub_matched_key]
                                        unwrapped = True
                                        break
                            if not unwrapped:
                                return None
                    elif isinstance(curr, list):
                        if tok.isdigit():
                            idx = int(tok)
                            if 0 <= idx < len(curr):
                                curr = curr[idx]
                            else:
                                return None
                        elif curr and isinstance(curr[0], dict):
                            # Auto-index first item if accessing property directly on list
                            sub_matched_key = next((k for k in curr[0] if k.lower() == tok.lower()), None)
                            if sub_matched_key is not None:
                                curr = curr[0][sub_matched_key]
                            else:
                                return None
                        else:
                            return None
                    else:
                        return None
                return curr

            step_var_pattern = r"\$step_(\d+)(?:(?:\.([a-zA-Z0-9_.\[\]]+))|(\[[^\]]+\](?:\.[a-zA-Z0-9_.]+)?))?"
            for k, v in params.items():
                if isinstance(v, str) and "$step_" in v:
                    exact_match = re.fullmatch(step_var_pattern, v.strip())
                    if exact_match:
                        prop_str = exact_match.group(2) or exact_match.group(3)
                        params[k] = _resolve_step_var(exact_match.group(1), prop_str)
                    else:
                        def _replace_match(m: re.Match) -> str:
                            prop_str = m.group(2) or m.group(3)
                            val = _resolve_step_var(m.group(1), prop_str)
                            return json.dumps(val) if isinstance(val, (dict, list)) else (str(val) if val is not None else "")

                        params[k] = re.sub(step_var_pattern, _replace_match, v)

            # Sanitize search queries interpolated from OCR text
            if action == "web_search" and "query" in params and isinstance(params["query"], str):
                raw_q = params["query"]
                # Strip markdown code blocks & backticks
                q_clean = re.sub(r"```[a-zA-Z]*\n?|```", " ", raw_q)
                cleaned_lines = []
                for line in q_clean.splitlines():
                    l_str = line.strip()
                    # Filter out isolated digits/dates and non-Latin artifacts (e.g. Marathi/Hindi dates)
                    if re.search(r"[a-zA-Z]{2,}", l_str):
                        cleaned_lines.append(l_str)
                if cleaned_lines:
                    q_clean = " ".join(cleaned_lines)
                for bad in [
                    "no legible text detected in this frame",
                    "no legible text detected",
                    "no legible text",
                    "no text detected",
                    "no visible text",
                    "no text could be extracted",
                ]:
                    q_clean = re.sub(rf"\b{re.escape(bad)}\b", "", q_clean, flags=re.IGNORECASE)
                params["query"] = re.sub(r"\s+", " ", q_clean).strip()

            res = await registry.execute_action(agent_name, action, params, context)
            results.append(res)
            step_outputs[f"step_{idx}"] = res.data or res.speech_summary

            # ── Confidence Gate: Vision/OCR → Research chains only ──────
            # If this step is a vision/OCR action and the NEXT step is a research step,
            # check the OCR confidence before blindly passing the result downstream.
            if (
                action in ("ocr_webcam", "ocr_screen", "inspect_webcam", "inspect_screen")
                and res.success
                and isinstance(res.data, dict)
                and idx < len(plan.steps)  # there is a next step
            ):
                next_step = plan.steps[idx]  # plan.steps is 0-indexed, idx is 1-indexed
                is_next_research = next_step.get("agent") == "research"
                confidence = res.data.get("confidence", "high")
                extracted = str(res.data.get("extracted_text") or "").strip()
                unreadable_patterns = [
                    "no legible text",
                    "no text detected",
                    "unable to detect",
                    "no visible text",
                    "no text could be extracted",
                    "no text found",
                ]
                is_unreadable = (
                    confidence in ("uncertain", "low")
                    or not extracted
                    or any(p in extracted.lower() for p in unreadable_patterns)
                )

                if is_next_research and is_unreadable:
                    # If OCR yielded no legible text on webcam, attempt inspect_webcam visual recognition before halting
                    if action == "ocr_webcam":
                        logger.info("[Planner] OCR yielded no legible text; attempting inspect_webcam visual recognition fallback...")
                        _ocr_query = params.get("query") or params.get("focus_hint") or "Identify the product or object the user is holding and describe it"
                        v_fallback = await registry.execute_action(
                            "vision",
                            "inspect_webcam",
                            {"query": f"Identify the product or object the user is holding and describe it: {_ocr_query}"},
                            context,
                        )
                        if (
                            v_fallback.success
                            and isinstance(v_fallback.data, dict)
                            and v_fallback.data.get("confidence") != "uncertain"
                            and v_fallback.data.get("description")
                        ):
                            logger.info(f"[Planner] Visual recognition fallback succeeded: {v_fallback.data.get('description')[:60]}")
                            # Use recognized item description for downstream research
                            results[-1] = v_fallback
                            v_fallback.data["extracted_text"] = v_fallback.data.get("description", "")
                            step_outputs[f"step_{idx}"] = v_fallback.data
                            continue

                    # Item is unreadable — ask user to reposition instead of hallucinating
                    logger.info(f"[Planner] Vision/OCR {action} confidence=uncertain: halting sequential chain, requesting repositioning.")
                    msg = (
                        "I'm having difficulty reading your display clearly, sir. Could you please zoom in or bring the window to focus?"
                        if "screen" in action
                        else "I'm having difficulty reading what you're holding clearly, sir. Could you hold it a bit closer to the camera, or face the label more directly toward me?"
                    )
                    clarify = SpecialistResult(
                        success=True,
                        action="confidence_gate",
                        agent_name="planner",
                        speech_summary=msg,
                        data={
                            "gate": "uncertain",
                            "extracted_text": res.data.get("extracted_text", "") or res.data.get("description", ""),
                        },
                        card_payload={
                            "type": "CAMERA_GUIDANCE",
                            "title": "Camera Repositioning Needed",
                            "suggestion": "Hold item closer and steady facing camera",
                        },
                    )
                    results.append(clarify)
                    # Return early — skip the research step
                    exec_ms = (time.perf_counter() - t0) * 1000
                    return ExecutionResult(
                        plan_type="sequential",
                        direct_response=clarify.speech_summary,
                        specialist_results=results,
                        execution_latency_ms=exec_ms,
                        provider_used=plan.provider_used,
                    )
                elif is_next_research and confidence == "medium":
                    # Partial read — proceed but log warning; Alfred will hedge in synthesis
                    logger.warning(
                        f"[Planner] OCR confidence=medium (text='{res.data.get('extracted_text', '')[:40]}'). "
                        "Proceeding with research but result may be imprecise."
                    )


        exec_ms = (time.perf_counter() - t0) * 1000
        return ExecutionResult(
            plan_type="sequential",
            specialist_results=results,
            execution_latency_ms=exec_ms,
            provider_used=plan.provider_used,
        )
